### ISSUE TITLE
[homebridge-tuya-webplatform] no config found, disabling pugins

### ISSUE THREAD

**Issue by jpoul27** [basdelfos/homebridge-tuya-web#11]
Hello, after start homebridge in cmd see this info:  [homebridge-tuya-webplatform] no config found, disabling pugins.

plugin installing command: "npm i homebridge-tuya-web -g" without erros

my config/

{
"bridge": {
"name": "switchkitchen1",
"username": "C4:C5:C6:C7:XX:XX",
"port": "8080",
"pin": "031-45-XXX"
},
"platform": "TuyaWebPlatform",
  "name": "TuyaWebPlatform",
  "options":
    {
      "username": "XXXXX@mail.ru",
      "password": "XXXXXX",
      "countryCode": "7",
      "platform": "smart_life",
      "pollingInterval": 10
    }
}

please help, what am i doing wrong?

**Comment by jpoul27** [comment]
![Untitled](https://user-images.githubusercontent.com/53563625/62344898-57a68080-b533-11e9-83c4-e57ff670dc8a.jpg)

**Comment by basdelfos** [comment]
Please post your whole config (without any credentials and such). I think you have configured the TuyaWebPlatform in the wrong section of the config.

**Comment by basdelfos** [comment]
And please use code formatting when posting the config, makes things a lot easier to read.

**Comment by jpoul27** [comment]
in the first post the whole config file.  I am not good at homebridge.  something else needs to be added to Config?

**Comment by mistirios** [comment]
Try this config:

{  
   "bridge":{  
      "name":"switchkitchen1",
      "username":"C4:C5:C6:C7:XX:XX",
      "port":"8080",
      "pin":"031-45-XXX"
   },
   "platforms":[  
      {  
         "platform":"TuyaWebPlatform",
         "name":"TuyaWebPlatform",
         "options":{  
            "username":"XXXXX@mail.ru",
            "password":"XXXXXX",
            "countryCode":"7",
            "platform":"smart_life",
            "pollingInterval":10
         }
      }
   ]
}

**Comment by jpoul27** [comment]
Thanks! now it worked

**Comment by JhumanJ** [comment]
I'm having the same issue here... My config file:

```
{
  "bridge": {
    "name": "Homebridge",
    "username": "C4:C5:C6:C7:CE:30",
    "port": "8080",
    "pin": "031-45-153"
  },
  "platforms": [
      {
         "platform":"TuyaWebPlatform",
         "name":"TuyaWebPlatform",
         "options":{
            "username":"*****@*****.net",
            "password":"******",
            "countryCode":"44",
            "platform":"tuya",
            "pollingInterval":10
         }
      }
  ]
}

```

**Comment by mistirios** [comment]
> I'm having the same issue here... My config file:
> 
> ```
> {
>   "bridge": {
>     "name": "Homebridge",
>     "username": "C4:C5:C6:C7:CE:30",
>     "port": "8080",
>     "pin": "031-45-153"
>   },
>   "platforms": [
>       {
>          "platform":"TuyaWebPlatform",
>          "name":"TuyaWebPlatform",
>          "options":{
>             "username":"*****@*****.net",
>             "password":"******",
>             "countryCode":"44",
>             "platform":"tuya",
>             "pollingInterval":10
>          }
>       }
>   ]
> }
> ```

Can you please post your log as well?

**Comment by JhumanJ** [comment]
My bad, misconfiguration,

**Comment by loewal** [comment]
Hi,
Can anyone check...no errors in JSON lint, but no config file found....???

{
        "platform": "TuyaWebPlatform",
        "name": "TuyaWebPlatform",
        "options": {
                "username": "lwalter@XXXXX.nl",
                "password": "XXXXXXXXX",
                "countryCode": "31",
                "platform": "smart_life",
                "pollingInterval": 10
        },

        "bridge": {
                "name": "Homebridge-Loe",
                "username": "CC:22:3D:E3:XX:XX",
                "port": 51826,
                "pin": "031-45-XXX"
        },

        "accessories": [{
                "accessory": "WeMo",
                "name": "Schakelaar",
                "description": "The Lamp in the Loungeroom",
                "wemo_name": "Schakelaar"
        }]

}


Thanks!

**Comment by tbrek** [comment]
@loewal wrong config. Move platform section to be part of bridge section of the JSON as per examples above.

**Comment by loewal** [comment]
Hi,
Made some changes, but still "no config found"....

{
        "bridge": {
                "name": "Homebridge-Loe",
                "username": "CC:22:3D:E3:XX:XX",
                "port": 51826,
                "pin": "031-45-XXX"
        },

        "platform": "TuyaWebPlatform",
        "name": "TuyaWebPlatform",
        "options": {
                "username": "lwalter@xxxxxxxxxx",
                "password": "xxxxxxxxx",
                "countryCode": "31",
                "platform": "smart_life",
                "pollingInterval": 10
        },
        "accessories": [{
                "accessory": "WeMo",
                "name": "Schakelaar",
                "description": "The Lamp in the Loungeroom",
                "wemo_name": "Schakelaar"
        }]
}

I bought a LSC Smart switch in a Dutch Action-shop and could add it to Google Home.
But want to use in in IOS of course.
Pls can anyone make the right changes?

Thnx!!

**Comment by mistirios** [comment]
Can you try this version please:

```
{
    "bridge": {
    "name": "Homebridge-Loe",
    "username": "CC:22:3D:E3:XX:XX",
    "port": 51826,
    "pin": "031-45-XXX"
    },
    "platforms": [
        {
            "platform": "TuyaWebPlatform",
            "name": "TuyaWebPlatform",
            "options": {
                    "username": "lwalter@xxxxxxxxxx",
                    "password": "xxxxxxxxx",
                    "countryCode": "31",
                    "platform": "smart_life",
                    "pollingInterval": 10
            }
        }],
    "accessories": [{
            "accessory": "WeMo",
            "name": "Schakelaar",
            "description": "The Lamp in the Loungeroom",
            "wemo_name": "Schakelaar"
    }]
}

```

**Comment by loewal** [comment]
Even stranger now:
I get an authentication-error on loginname/password. Changed it in the ios-app and in config.json.
Deleted subdirectories and restarted homebridge..
Same error...


[17-2-2020 12:51:45] [TuyaWebPlatform] Error: Authentication fault: Get accesstoken failed. Username or password error!
feb 17 12:51:45 cubie homebridge[15260]:     at Request.request [as _callback] (/root/node_modules/homebridge-tuya-web/lib/tuyawebapi.js:221:30)
feb 17 12:51:45 cubie homebridge[15260]:     at Request.self.callback (/root/node_modules/request/request.js:185:22)
feb 17 12:51:45 cubie homebridge[15260]:     at Request.emit (events.js:189:13)
feb 17 12:51:45 cubie homebridge[15260]:     at Request.<anonymous> (/root/node_modules/request/request.js:1154:10)
feb 17 12:51:45 cubie homebridge[15260]:     at Request.emit (events.js:189:13)
feb 17 12:51:45 cubie homebridge[15260]:     at IncomingMessage.<anonymous> (/root/node_modules/request/request.js:1076:12)
feb 17 12:51:45 cubie homebridge[15260]:     at Object.onceWrapper (events.js:277:13)
feb 17 12:51:45 cubie homebridge[15260]:     at IncomingMessage.emit (events.js:194:15)
feb 17 12:51:45 cubie homebridge[15260]:     at endReadableNT (_stream_readable.js:1103:12)
feb 17 12:51:45 cubie homebridge[15260]:     at process._tickCallback (internal/process/next_tick.js:63:19)

**Comment by loewal** [comment]
I registered in the Tuya-app and used these values to login.
No problem until last config.....
Changed password and tried again. No luck..

**Comment by mistirios** [comment]
change your config from `"platform": "smart_life"`
to `"platform": "tuya"`
> I registered in the Tuya-app and used these values to login.
> No problem until last config.....
> Changed password and tried again. No luck..

**Comment by loewal** [comment]
Thanks Mistirios. That worked.
I hardly find any examples of adding a tuya-device. In my case a switchable wall-outlet.
Do I have to add it, like I configured it on the Tuya website?

**Comment by loewal** [comment]
But no switch...hereby two configs...not working

{
	"bridge": {
		"name": "Homebridge-Loe",
		"username": "CC:22:3D:E3:CE:30",
		"port": 51826,
		"pin": "031-45-154"
	},
	"accessories": [{
		"accessory": "WeMo",
		"name": "Schakelaar",
		"description": "The Lamp in the Loungeroom",
		"wemo_name": "Schakelaar"
	}],
	"platforms": {
		"platform": "TuyaWebPlatform",
		"name": "TuyaWebPlatform",
		"options": {
			"username": "lwalter@xxxxxxx",
			"password": "xxxxxxxx",
			"countryCode": "31",
			"platform": "tuya",
			"pollingInterval": 10
		},
		"defaults": [{
			"id": "6yqo0llacb808rv5",
			"device_type": "Switch 10a"
		}]
	}
}

or

{
        "bridge": {
                "name": "Homebridge-Loe",
                "username": "CC:22:3D:E3:CE:30",
                "port": 51826,
                "pin": "031-45-154"
        },
        "platforms": {
                "platform": "TuyaWebPlatform",
                "name": "TuyaWebPlatform",
                "options": {
                        "username": "lwalter@home.nl",
                        "password": "&asublo19",
                        "countryCode": "31",
                        "platform": "tuya",
                        "pollingInterval": 10
                },
                "defaults": [{
                        "id": "6yqo0llacb808rv5",
                        "device_type": "Switch 10a"
                }],
                "accessories": [{
                        "accessory": "WeMo",
                        "name": "Schakelaar",
                        "description": "The Lamp in the Loungeroom",
                        "wemo_name": "Schakelaar"
                }]
        }
}

My 'Schakelaar' also disappeared.

Can you help?

**Comment by loewal** [comment]
Oops...password

**Comment by mistirios** [comment]
@loewal Remove 
```
"defaults": [{
"id": "6yqo0llacb808rv5",
"device_type": "Switch 10a"
}],
``` 
from your config. Just add the device to your tuya account using tuya-app add it will automatic  appear  in your homebridge.

**Comment by loewal** [comment]
This is my output:
feb 17 19:22:10 cubie homebridge[768]: [17-2-2020 19:22:10] Loaded plugin: homebridge-nest
feb 17 19:22:10 cubie homebridge[768]: [17-2-2020 19:22:10] Registering platform 'homebridge-nest.Nest'
feb 17 19:22:10 cubie homebridge[768]: [17-2-2020 19:22:10] ---
feb 17 19:22:14 cubie homebridge[768]: [17-2-2020 19:22:14] Loaded plugin: homebridge-wemo
feb 17 19:22:14 cubie homebridge[768]: [17-2-2020 19:22:14] Registering accessory 'homebridge-wemo.WeMo'
feb 17 19:22:14 cubie homebridge[768]: [17-2-2020 19:22:14] ---
feb 17 19:22:17 cubie homebridge[768]: [17-2-2020 19:22:17] Loaded plugin: homebridge-tuya-web
feb 17 19:22:17 cubie homebridge[768]: [17-2-2020 19:22:17] Registering platform 'homebridge-tuya-web.TuyaWebPlatform'
feb 17 19:22:17 cubie homebridge[768]: [17-2-2020 19:22:17] ---
feb 17 19:22:17 cubie homebridge[768]: [17-2-2020 19:22:17] Loading 1 platforms...
feb 17 19:22:17 cubie homebridge[768]: [17-2-2020 19:22:17] [TuyaWebPlatform] Initializing TuyaWebPlatform platform...
feb 17 19:22:17 cubie homebridge[768]: [17-2-2020 19:22:17] Loading 1 accessories...
feb 17 19:22:17 cubie homebridge[768]: [17-2-2020 19:22:17] [Schakelaar] Initializing WeMo accessory...
feb 17 19:22:17 cubie homebridge[768]: [17-2-2020 19:22:17] [Schakelaar] Searching for WeMo device with exact name 'Schakelaar'...
feb 17 19:22:18 cubie homebridge[768]: Setup Payload:
feb 17 19:22:18 cubie homebridge[768]: X-HM://0023ISYWYIA4H
feb 17 19:22:18 cubie homebridge[768]: Scan this code with your HomeKit app on your iOS device to pair with Homebridge:
feb 17 19:22:18 cubie homebridge[768]:
feb 17 19:22:18 cubie homebridge[768]:
feb 17 19:22:18 cubie homebridge[768]:
feb 17 19:22:18 cubie homebridge[768]:
feb 17 19:22:18 cubie homebridge[768]:
feb 17 19:22:18 cubie homebridge[768]:
feb 17 19:22:18 cubie homebridge[768]:
feb 17 19:22:18 cubie homebridge[768]:
feb 17 19:22:18 cubie homebridge[768]:
feb 17 19:22:18 cubie homebridge[768]:
feb 17 19:22:18 cubie homebridge[768]:
feb 17 19:22:18 cubie homebridge[768]:
feb 17 19:22:18 cubie homebridge[768]:
feb 17 19:22:18 cubie homebridge[768]:
feb 17 19:22:18 cubie homebridge[768]:
feb 17 19:22:18 cubie homebridge[768]:
feb 17 19:22:18 cubie homebridge[768]:
feb 17 19:22:18 cubie homebridge[768]:
feb 17 19:22:18 cubie homebridge[768]:
feb 17 19:22:18 cubie homebridge[768]:
feb 17 19:22:18 cubie homebridge[768]:
feb 17 19:22:18 cubie homebridge[768]:
feb 17 19:22:18 cubie homebridge[768]:
feb 17 19:22:18 cubie homebridge[768]:
feb 17 19:22:18 cubie homebridge[768]:
feb 17 19:22:18 cubie homebridge[768]:
feb 17 19:22:18 cubie homebridge[768]:
feb 17 19:22:18 cubie homebridge[768]: Or enter this code with your HomeKit app on your iOS device to pair with Homebridge:
feb 17 19:22:18 cubie homebridge[768]:
feb 17 19:22:18 cubie homebridge[768]:     ┌────────────┐
feb 17 19:22:18 cubie homebridge[768]:     │ 031-45-154 │
feb 17 19:22:18 cubie homebridge[768]:     └────────────┘
feb 17 19:22:18 cubie homebridge[768]:
feb 17 19:22:18 cubie homebridge[768]: [17-2-2020 19:22:18] [TuyaWebPlatform] Initializing TuyaWebPlatform...
feb 17 19:22:18 cubie homebridge[768]: [17-2-2020 19:22:18] Homebridge is running on port 51826.
feb 17 19:22:19 cubie homebridge[768]: [17-2-2020 19:22:19] [Schakelaar] Found 'Schakelaar' device at 10.0.0.19

But: no device found at all now....there must be some mistake I think in my config.json;

{
    "bridge": {
    "name": "Homebridge-Loe",
    "username": "CC:22:3D:E3:CE:30",
    "port": 51826,
    "pin": "031-45-154"
    },
    "platforms": [
        {
            "platform": "TuyaWebPlatform",
            "name": "TuyaWebPlatform",
            "options": {
                    "username": "lwalter@home.nl",
                    "password": "&asublo19",
                    "countryCode": "31",
                    "platform": "tuya",
                    "pollingInterval": 10
            }
        }],
    "accessories": [{
            "accessory": "WeMo",
            "name": "Schakelaar",
            "description": "The Lamp in the Loungeroom",
            "wemo_name": "Schakelaar"
    }]
}

Can you - if you don't mind - check this?
I'm a newbie in json etc....

**Comment by mistirios** [comment]
@loewal There are no errors in your log and your config looks correct. It seems like you have no registered devices in your Tuya account. Does your device appearing in your mobile Tuya-app?

You must first pair your device with your phone (following app instructions).

**Comment by loewal** [comment]
Working now!!!
I appeared, that my Homebridge hub/bridge was already registered in my iPhone.
Normally i just needed to delete the hub in the "Schakelaar'. Now I had to do it in the Home-properties/hubs and bridges.
Also i Had te reinstall the homebridge-tuya-web plugin en uninstall the hoembridge-tuya plugin.

Thank you very much
Grtz. Loe

**Comment by JRNNL** [comment]
Hi guys!

I used the TuyaWebPlatform plugin for homebridge for a while, until it stopped working about two weeks ago. The devices are still in my Home app on my iphone, but are not responding anymore when trying to turn them on and off. The devices are working through the Tuya app, though. 

This is my config below. As you can see, I'm using multiple plugins, and all of them work, besides TuyaWeb:

{
	"bridge": {
		"name": "Homebridge",
		"username": "CC:22:3D:E3:CE:30",
		"port": 51826,
		"pin": "031-45-154"
	},
	"platforms": [{
			"platform": "config",
			"name": "Config",
			"port": 8085,
			"sudo": true,
			"log": {
				"method": "systemd",
				"service": "homebridge"
			}
		},
		{
			"platform": "Nest",
			"googleAuth": {
				"issueToken": "xxxxxxxxx"
			},
			"options": [
				"HomeAway.Disable",
				"Thermostat.Eco.Disable"
			]
		},
		{
			"platform": "Camera-IP",
			"cameras": [{
				"name": "Huiskamer",
				"videoConfig": {
					"source": "-re -i http://192.168.178.213:8081",
					"stillImageSource": "-i http://192.168.178.213:8765/picture/1/current/",
					"maxStreams": 1,
					"maxWidth": 1280,
					"maxHeight": 720,
					"maxFPS": 30
				}
			}]
		},
		{
			"platform": "TuyaWebPlatform",
			"name": "TuyaWebPlatform",
			"options": {
				"username": "xxxxxxxx@gmail.com",
				"password": "xxxxxxxx",
				"countryCode": "31",
				"platform": "tuya",
				"pollingInterval": 5
			}
		}
	],
	"accessories": []
}

The log file says it does cannot authorize, but I did not change my username or password in the app.

[3/11/2020, 12:55:27 AM] Registering platform 'homebridge-nest.Nest'
[3/11/2020, 12:55:27 AM] ---
[3/11/2020, 12:55:27 AM] Loaded plugin: homebridge-tuya-web
[3/11/2020, 12:55:27 AM] Registering platform 'homebridge-tuya-web.TuyaWebPlatform'
[3/11/2020, 12:55:27 AM] ---
[3/11/2020, 12:55:27 AM] Loading 4 platforms...
[3/11/2020, 12:55:27 AM] [Config] Initializing config platform...
[3/11/2020, 12:55:27 AM] [Config] Spawning homebridge-config-ui-x with PID 17918
[3/11/2020, 12:55:27 AM] [Nest] Initializing Nest platform...
[3/11/2020, 12:55:27 AM] [Nest] Fetching Nest devices.
[3/11/2020, 12:55:27 AM] [Camera-IP] Initializing Camera-IP platform...
[3/11/2020, 12:55:27 AM] [TuyaWebPlatform] Initializing TuyaWebPlatform platform...
[3/11/2020, 12:55:27 AM] Loading 0 accessories...
[3/11/2020, 12:55:27 AM] [TuyaWebPlatform] Configuring cached accessory [Computerkamer ] bfb5c835e4feb9e452f8hm 6c35ed99-8854-4c31-bcfd-75f567fedf45
[3/11/2020, 12:55:27 AM] [TuyaWebPlatform] Configuring cached accessory [Badkamer] bf13f55fb4b33267ebhuf4 b241a6b4-03d0-497d-bff6-281778b8a0f9
[3/11/2020, 12:55:27 AM] [TuyaWebPlatform] Configuring cached accessory [Woonkamer] bf8f7e8c84c75b746b8fjl c9dfa17e-90fd-4052-a3a4-2e0b5e725cef
[3/11/2020, 12:55:27 AM] [TuyaWebPlatform] Configuring cached accessory [Keuken rechts] 33360064c44f33929916 4b06102d-8e72-4310-8b31-1cce417d400f
[3/11/2020, 12:55:27 AM] [TuyaWebPlatform] Configuring cached accessory [Keuken links] 33360064600194d687c1 25586f79-4376-4dbe-9169-77a9784ec147
[3/11/2020, 12:55:27 AM] [TuyaWebPlatform] Configuring cached accessory [Slaapkamer rechts] 05074754c44f33af1f95 a88023f2-bf23-4a44-9d83-19739da88583
[3/11/2020, 12:55:27 AM] [TuyaWebPlatform] Configuring cached accessory [Slaapkamer links] 05074754c44f33af1f07 becd52af-f4fd-40c1-9bcc-23cf22ebbdf3
[3/11/2020, 12:55:27 AM] [TuyaWebPlatform] Initializing TuyaWebPlatform...
[3/11/2020, 12:55:27 AM] Huiskamer is running on port 38135.
[3/11/2020, 12:55:27 AM] Please add [Huiskamer] manually in Home app. Setup Code: 031-45-154
[3/11/2020, 12:55:28 AM] [TuyaWebPlatform] Error: Authentication fault: Get accesstoken failed. Username or password error!
    at Request._callback (/usr/lib/node_modules/homebridge-tuya-web/lib/tuyawebapi.js:221:30)
    at Request.self.callback (/usr/lib/node_modules/homebridge-tuya-web/node_modules/request/request.js:185:22)
    at Request.emit (events.js:311:20)
    at Request.<anonymous> (/usr/lib/node_modules/homebridge-tuya-web/node_modules/request/request.js:1161:10)
    at Request.emit (events.js:311:20)
    at IncomingMessage.<anonymous> (/usr/lib/node_modules/homebridge-tuya-web/node_modules/request/request.js:1083:12)
    at Object.onceWrapper (events.js:417:28)
    at IncomingMessage.emit (events.js:323:22)
    at endReadableNT (_stream_readable.js:1204:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)

Who can help me further?!

**Comment by loewal** [comment]
Hi,
Your config is ok. Checked it at https://jsonlint.com/ <https://jsonlint.com/>

You could try the following:

Remove the following folders:
Accessories and persist under /var/lib/homebridge (my configuration…)

Then delete your devices on your iPhone and restart Homebridge.
Then go discover your devices again on your iPhone.

I do this quite regularly when something doesn’t work anymore.

Success!!

Loe
