### ISSUE TITLE
Discovers A19 bulbs in Smart Life app, but not PAR38 or PAR20

### ISSUE THREAD

**Issue by simmonsjohnr** [basdelfos/homebridge-tuya-web#13]
Starting Homebridge, the plugin discovered 2 of my Tuya smart bulbs (registered in the Smart Life app), but doesn't find 10 bulbs.  All 12 are in the Smart Life app, but only the 2 A19 bulbs are found whereas the PAR38 and PAR20 bulbs aren't found (spotlights).  They all use the same coding, don't they??  Any ideas why it would find the 2 but not the others?  Thank you.  

PS. This product is discovered perfectly:
https://www.amazon.com/gp/product/B07RSR9LHY/ref=ppx_yo_dt_b_asin_title_o01_s01?ie=UTF8&psc=1
whereas this one isn't:
https://www.amazon.com/gp/product/B07NVYKBQB/ref=ppx_yo_dt_b_asin_title_o01_s02?ie=UTF8&psc=1

Both use the Smart Life app.

**Comment by basdelfos** [comment]
I think that your PAR38 and PAR29 bulbs use another type in the Tuya Web API that is not recognized by the plugin yet.

**Comment by basdelfos** [comment]
Can you post the output that is generated by `node discover` when using the CLI tool that I have created. See https://github.com/basdelfos/tuya-web-cli.
Please specify which devices are the ones that don't show up in the Homebridge plugin.

**Comment by simmonsjohnr** [comment]
_Thank you for looking at this:_

Discovering Tuya devices...
Login successful.
Discovered devices:
[ { data:
     { brightness: '255',
       color_mode: 'white',
       color: [Object],
       online: true,
       state: 'false',
       color_temp: 2694 },
    name: 'Torch Lamp ',
    icon:
     'https://images.tuyaus.com/smart/program_category_icon/dj.png',
    id: '62733760bcddc2a112fa',
    dev_type: 'light',
    ha_type: 'light' },
  { data:
     { brightness: '255',
       color_mode: 'white',
       color: [Object],
       online: true,
       state: 'false',
       color_temp: 2694 },
    name: 'Torch Lamp',
    icon:
     'https://images.tuyaus.com/smart/program_category_icon/dj.png',
    id: '60707618ecfabc9a2d7f',
    dev_type: 'light',
    ha_type: 'light' },
  { data:
     { brightness: '255',
       color_mode: 'colour',
       color: [Object],
       online: true,
       state: 'false',
       color_temp: 4988 },
    name: 'Chicken Light 1',
    icon:
     'https://images.tuyaus.com/smart/program_category_icon/dj.png',
    id: '6070761884f3eb3a8804',
    dev_type: 'light',
    ha_type: 'light' } ]

**Comment by simmonsjohnr** [comment]
I now have 3 bulbs that are recognized (I added one since my original message).  None of the PAR38 or PAR30 bulbs show up.  Thank you.

**Comment by basdelfos** [comment]
Thanks for posting the output. So, your PAR38 and PAR20 devices are not listed in the output? Than these device types are not supported by the Tuya Web API that Home Assistant uses, and unfortunately I can’t do anything to get them supported.

**Comment by simmonsjohnr** [comment]
Gotcha. Thanks for checking.
