### ISSUE TITLE
Control light color

### ISSUE THREAD

**Issue by niksauer** [basdelfos/homebridge-tuya-web#14]
Does Tuya's API provide the ability to also change a light's color instead of only on/off and dimming? I'd like to contribute some code 🤔

**Comment by basdelfos** [comment]
Yes it does, I didn’t implement it yet because I don’t own a device to test.
Take a look at the python library from Home Assistant how things work.

Link: https://github.com/PaulAnnekov/tuyaha

Additions to the plugin are greatly appreciated, when finished and tested, please make a pull request.

**Comment by Torac2** [comment]
@basdelfos if you add it to the homebridge plugin ill test it for you. :)

**Comment by jsalexjs** [comment]
Cant wait for Colour to be supported @basdelfos Thanks so much for finally getting Tuya devices working again on Homebridge, and easier than ever!

**Comment by basdelfos** [comment]
@jsalexjs can you post the output of `node discover` when using the CLI tool that I have created, see https://github.com/basdelfos/tuya-web-cli. That will probably help with figuring out which fields to set to control other properties than only switching on/off.

**Comment by niksauer** [comment]
Here's the output for my RGBW light strip:
```
[ { data:
     { brightness: '255',
       color_mode: 'colour',
       color: [Object],
       online: true,
       state: 'true' },
    name: 'LED Leiste IP67',
    icon:
     'https://images.tuyaeu.com/smart/icon/1547100216u85vcx92bm9_0.png',
    id: 'bfacbb462f2a0503d4wizi',
    dev_type: 'light',
    ha_type: 'light' } ]
```

I'll start looking Home Assistant implementation now.
