### ISSUE TITLE
Freeze on Initializing TuyaWebPlatform

### ISSUE THREAD

**Issue by yuliwilliam** [basdelfos/homebridge-tuya-web#15]
[2019-8-4 06:55:59] [TuyaWebPlatform] Initializing TuyaWebPlatform...
[2019-8-4 06:55:59] Homebridge is running on port 51826.

the plugin freezes when HomeBridge runs automatically on bootup, but it works fine when I manually run it afterward.
it might be the plugin tries to get access to the network(I use wifi) before the system connects to it.

**Comment by basdelfos** [comment]
Strange, the plugin starts discovering devices after Homebridge reports it is ready starting up. The network should be ready by then, I suppose. But I have red about this issue before for other apps running on boot up on a rpi. Try searching the internet for a solution, there are options to delay the startup of programs during boot.

**Comment by yuliwilliam** [comment]
just for additional information, works perfect on wired connection on bootup
