### ISSUE TITLE
Switch not recognized (outlets work fine)

### ISSUE THREAD

**Issue by basti184** [basdelfos/homebridge-tuya-web#16]
Hi, 
I have just tested the plugin and noticed that my 3 power outlets (embedded in Smart Life) are recognized and working fine. However I have one switch embedded which doesn‘t appear at all in the Home App. The switch works fine from the Smart Life app. 

Here is a link to the device not working: 
https://www.amazon.de/Didikit-Empfänger-Fernbedienung-Intelligentes-Kompatibel/dp/B07J27Y4VY

Thanks

**Comment by basdelfos** [comment]
Hi, can you post the output of node discover when using the CLI tool that I have created, see https://github.com/basdelfos/tuya-web-cli.

**Comment by basti184** [comment]
Sorry for the newbie question (I’m new to this) but I can‘t get it to work. I get the following when at install step 3: 

pi@raspberrypi:/home/tuya-web-cli $ npm i
npm WARN saveError ENOENT: no such file or directory, open '/home/tuya-web-cli/package.json'
npm WARN enoent ENOENT: no such file or directory, open '/home/tuya-web-cli/package.json'
npm WARN tuya-web-cli No description
npm WARN tuya-web-cli No repository field.
npm WARN tuya-web-cli No README data
npm WARN tuya-web-cli No license field.

up to date in 0.796s
found 0 vulnerabilities


Anything I am missing out?
Thanks

**Comment by basdelfos** [comment]
Solved, somehow the package.json did not get included in the git repository and I didn't notice it.

**Comment by basti184** [comment]
Thanks, I was able to run it now. 
However I only see the 3 working devices there as well. Not the one switch missing. 

Login successful.
Discovered devices:
[ { data: { online: true, state: true },
    name: 'Emilia Fernseher',
    icon: 'https://images.tuyaeu.com/smart/icon/1499760092_0.png',
    id: '01200462ecfabc0ff7ef',
    dev_type: 'switch',
    ha_type: 'switch' },
  { data: { online: true, state: false },
    name: 'Wohnzimmerlampe',
    icon: 'https://images.tuyaeu.com/smart/icon/1499760092_0.png',
    id: '012004092c3ae844a552',
    dev_type: 'switch',
    ha_type: 'switch' },
  { data: { online: true, state: false },
    name: 'Anlage',
    icon: 'https://images.tuyaeu.com/smart/icon/1499760092_0.png',
    id: '01200462ecfabc0fc9b8',
    dev_type: 'switch',
    ha_type: 'switch' } ]

I have also attached a screenshot of my Smart Life App
![65878C40-4E50-4FE7-BABF-FEDAA89CC513](https://user-images.githubusercontent.com/53945090/62819715-4e339e80-bb59-11e9-92dd-cbc9d0055fb6.jpeg)

**Comment by basdelfos** [comment]
Seems like your switch is not supported by the Tuya Web API that Home Assistant uses.

**Comment by basti184** [comment]
Ok, too bad. I will anyways continue to use the plugin for my other devices because I like the idea of not adding new devices manually. Good job!
Thanks
