### ISSUE TITLE
Outlet no update if manual off

### ISSUE THREAD

**Issue by cilianospina** [basdelfos/homebridge-tuya-web#17]
if I turn on the device manually or from the TUYA application, it is updated on in homekit, but if I manually turn off the device or from the TUYA application, it is not updated off on homekit
![539AB812-C8A5-491B-9A5B-CEC0E4218DCD](https://user-images.githubusercontent.com/53990473/62830831-e32aac00-bbda-11e9-81ff-2f086381f265.jpeg)
![63B0A254-05B9-4584-8782-C928FFBD0428](https://user-images.githubusercontent.com/53990473/62830832-e3c34280-bbda-11e9-9b23-16915a3fd971.jpeg)

**Comment by basdelfos** [comment]
Thanks for reporting this issue. I have fixed the issue (noticed it today also). You can download version 0.1.5 from npmjs with this fix.
