### ISSUE TITLE
Shutter Homekit

### ISSUE THREAD

**Issue by stylearoma** [basdelfos/homebridge-tuya-web#20]
Hello,

I was able to read out all the necessary information via Charles Proxy. Is there a way to add the blinds to Homekit? Unfortunately, he finds the device, but is not displayed.

"[TuyaLan] Failed to discover Rollo (MA6aYCA........) in time but will keep looking."

https://www.amazon.de/gp/product/B07H9PSQCN/ref=ppx_yo_dt_b_asin_title_o02_s00?ie=UTF8&psc=1

**Comment by cilianospina** [comment]
that device does not work with TUYA app

**Comment by PierreBrisorgueil** [comment]
it work with Smart Life (ref comment) so probably with Tuya. 

The problem is probably here, curtains are not supported yet : https://github.com/basdelfos/homebridge-tuya-web/issues/9

**Comment by basdelfos** [comment]
Yep indeed seems to be related to the support of covers/curains.
