### ISSUE TITLE
Support for Scenes

### ISSUE THREAD

**Issue by tonysprenk** [basdelfos/homebridge-tuya-web#21]
In the Tuya app it is possible to make scenes. It would be nice to have a simple on/off switch in the home app that triggers a Tuya scene. This way unsupported devices (like curtains) can be added to a scene and controlled through the home app. This wouldn’t give full control but would at least be a way to somewhat control unsupported devices. It would be nice to be able to have the ability to trigger a scene when the switch is turned on and a different scene when the switch is turned off. I can test this if necessary.

**Comment by basdelfos** [comment]
As mentioned in the readme, I don't suspect to implement scenes any soon as it is more logical to define scenes in the iOS Home App.
