### ISSUE TITLE
dimmers brightness

### ISSUE THREAD

**Issue by avsimankov** [basdelfos/homebridge-tuya-web#23]
i''m added smartlife dimmers (3 devices). When i trying to set brightness, in example 70%(or any other) it's set correctly, but when come time of refresh interval homebridge set brightness to 0

**Comment by avsimankov** [comment]
setting additional device_type to dimmer solved issue

**Comment by uberfunk** [comment]
Thank you, I had this same issue. 
@basdelfos can this be fixed or implemented somehow?
