### ISSUE TITLE
Can I request to please add Tuya IR remote?

### ISSUE THREAD

**Issue by chadman4** [basdelfos/homebridge-tuya-web#3]
1. Can I request to please add device for Tuya universal IR remote?
Something like this:
https://www.lazada.com.ph/products/lasco-wifi-ir-micro-universal-remote-control-for-tv-aircon-and-other-ir-devices-compatible-with-alexa-google-home-google-assistant-and-ifttt-i270470034-s388410144.html?ef_id=Cj0KCQjwyerpBRD9ARIsAH-ITn91UvFlwJOjYjhQ9kte7rsp1evIVc9NdfZi5kp_ESYsC08cKqnOKIgaAs53EALw_wcB:G:s&s_kwcid=AL!3151!3!244365264139!!!u!296303633664!&exlaz=d_1:mm_150050845_51350205_2010350205::12:1032129542!52512091404!!!pla-296303633664!c!296303633664!388410144!124912004&gclid=Cj0KCQjwyerpBRD9ARIsAH-ITn91UvFlwJOjYjhQ9kte7rsp1evIVc9NdfZi5kp_ESYsC08cKqnOKIgaAs53EALw_wcB

2. Would it be possible to add the electricity readout in the smart switch?

**Comment by basdelfos** [comment]
I took a brief look at remote IR support, there is no remote IR support in the Web API that this plugin uses. So, as of writing it is not possible to implement this feature, maybe in the future when the Web API also supports IR remotes.
