### ISSUE TITLE
 No valid token     at TuyaWebApi.discoverDevices 

### ISSUE THREAD

**Issue by Paschalis** [basdelfos/homebridge-tuya-web#4]
I do get the following issue:
```
(node:11822) UnhandledPromiseRejectionWarning: Error: No valid token
    at TuyaWebApi.discoverDevices (/usr/local/lib/node_modules/homebridge-tuya-web/lib/tuyawebapi.js:50:13)
    at /usr/local/lib/node_modules/homebridge-tuya-web/index.js:62:27
    at processTicksAndRejections (internal/process/task_queues.js:85:5)
(node:11822) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was
not handled with .catch(). (rejection id: 1)
(node:11822) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

If you need any futher debug info please let me know.
My configuration entry is like:

{
      "platform": "TuyaWebPlatform",
      "name": "TuyaWebPlatform",
      "options":
      {
        "username": "<EMAIL_ADDRESS>",
        "password": "<PASSWORD>",
        "countryCode": "<COUNTRY_CODE>",
        "platform": "smart_life",
        "pollingInterval": 10
      }
    }

**Comment by basdelfos** [comment]
Looking at the error `Error: No valid token` it looks like your credentials are not correct. Do you use the Smart Life app on your mobile device?  You will need to fill in the exact same username/password. If you are using another app on your mobile device, than you will need to change the option `platform:` to the name of the app you are using. See readme for available platforms.

**Comment by basdelfos** [comment]
I've made some changes to  catch any errors that occur during login.
Publishing version 0.1.2 with this change.
