### ISSUE TITLE
Blitzwolf Led Strip BW-LT11 & BW-LT21 (RGBW) - some issues

### ISSUE THREAD

**Issue by peros550** [basdelfos/homebridge-tuya-web#43]
Hi, 

many thanks for this plugin. It makes our life much easier. I tried with Blitzwolf led strip BW-LT11 and it can control ON/OFF and dimming capability. 

However, when you wish to control color , then operation does not work very well. Although it looks like something is happening and color do change, they look washed out. Maybe, because Blitzwolf led strip has another parameter (Saturation) and probably the plugin does not set this correctly hence the washed out effect. 

Also, another issue I would like to report has to do with light intensity reported through Home app. Although you are able to control light intensity, a few seconds after (probably at poll interval) the percent reported in Home app is falsely 0% although the actual value could be anything between 1% - 100% .

Thanks for your time. If there is something I can to do to help, please let me know.

**Comment by gashead76** [comment]
I have this issue as well, but with some “Merkury” bulbs I have. I’ve just been using the TuyaSmart app to set the colors/saturation I want and then I don’t touch the HomeKit color controls. I haven’t found a fix yet... They all exhibit this behavior. When changing the color on the strips via Home the saturation always gets set to 39% for whatever reason.

I’d love to figure how to fix this, I far prefer this Homebridge plugin to using Home Assistant in conjunction with Homebridge. It is considerably faster and I don’t have to run an entire other home automation system.

**Comment by peros550** [comment]
@basdelfos Many thanks for all your efforts :)   

I just bought an RGBW light bulb from Blitzwolf (BW-LT21) and have exactly the same issues as mentioned above with the led strip (BW-LT21).  
The only function which work well is ON/OFF & Dimming through Home app. 

If you try to change color then 9/10 the color illuminated on the bulb is not the one you selected within Home app. Also, it's not possible to select the White color through Home app. To do that, you would need to use again Tuya app. 

Is something we could do to help you with the plugin development?

**Comment by peros550** [comment]
closing as this repository is not actively maintained any more. 
Whoever is interested can follow the below two links and change factory firmware on BW-LT11 to an  open source that runs homekit natively: 

https://github.com/RavenSystem/esp-homekit-devices/issues/683

and then use this json: {"c":{"b":[{"g":0,"t":5}]},"a":[{"t":30,"r":4,"g":12,"v":14,"w":5,"b":[{"g":0}]}]}
