### ISSUE TITLE
“Slow” response

### ISSUE THREAD

**Issue by tonysprenk** [basdelfos/homebridge-tuya-web#6]
Before using this plugin I was using home assistant. On home assistant the response time from switching a device on in the ui or home app would be really slow (like 30 secs) and sometimes it wouldn’t respond at all. I always thought this was due to the special “link” that HA uses for the Tuya cloud. But this plugin uses the same method and it’s much more stable and allot faster (few seconds max). But it is still not as fast as the Tuya App which is almost always instant. So now I’m wondering; is the few second delay due to the connection with the Tuya cloud or could the code somehow be sped up?

**Comment by basdelfos** [comment]
Thank you for using the plugin.
I also was using home assistant with Tuya before and also noticed that there was a delay in toggling lights and the actual device responding. But that was only a few seconds at last for me. Homebridge is much faster, actually as fast as the Smart Life plugin (or no noticeable difference).

There are some benefits to make this plugin faster as it now uses the Tuya Web API servers located in the EU. If you are outside the EU, this can have some delay as the communication has to go through more hops to reach other sides of the world.

When a token is created it has the region into the returned token, I have still need to implement that after the token is received the servers in the region of the token are used for all other requests.

I will implement this in the coming weeks and report back when you can test if this has a performance improvement.

**Comment by basdelfos** [comment]
I couldn't resist, see here:

https://github.com/basdelfos/homebridge-tuya-web/tree/regional-tuya-servers

I've made some unit tests to test the code, it seems to be working for me, but I already used local EU server, so not much has changed when I run the tests.

Can you test this code on your environment, unittest or in homebridge?

**Comment by tonysprenk** [comment]
I’m living in Europe so probably it is already automatically using the EU server?

**Comment by basdelfos** [comment]
Ok, if you live in the EU, then this change does not have any effect on latency, as the current code already uses the EU servers.

**Comment by basdelfos** [comment]
There isn’t any more to speed up in the plugin code. It performs almost instantly for me. Could be that your hardware, network or internet connection is the bottleneck. I run homebridge in a docker on a RPI 3B (cable, no WiFi).
