### ISSUE TITLE
Crash Homebridge

### ISSUE THREAD

**Issue by kalety** [basdelfos/homebridge-tuya-web#7]
Hi! you plugion crash the homebridge instance.... Thank you for your work!!!

 at Request.request [as _callback] (/usr/local/lib/node_modules/homebridge-tuya-web/lib/tuyawebapi.js:208:89)
Jul 31 13:40:34 COTO-HB2 homebridge[2982]:     at self.callback (/usr/local/lib/node_modules/homebridge-tuya-web/node_modules/request/request.js:185:22)
Jul 31 13:40:34 COTO-HB2 homebridge[2982]:     at Request.emit (events.js:198:13)
Jul 31 13:40:34 COTO-HB2 homebridge[2982]:     at Request.onRequestError (/usr/local/lib/node_modules/homebridge-tuya-web/node_modules/request/request.js:881:8)
Jul 31 13:40:34 COTO-HB2 homebridge[2982]:     at ClientRequest.emit (events.js:198:13)
Jul 31 13:40:34 COTO-HB2 homebridge[2982]:     at TLSSocket.socketErrorListener (_http_client.js:392:9)
Jul 31 13:40:34 COTO-HB2 homebridge[2982]:     at TLSSocket.emit (events.js:198:13)
Jul 31 13:40:34 COTO-HB2 homebridge[2982]:     at emitErrorNT (internal/streams/destroy.js:91:8)
Jul 31 13:40:34 COTO-HB2 homebridge[2982]:     at emitErrorAndCloseNT (internal/streams/destroy.js:59:3)
Jul 31 13:40:34 COTO-HB2 homebridge[2982]:     at process._tickCallback (internal/process/next_tick.js:63:19)
Jul 31 13:40:34 COTO-HB2 homebridge[2982]: [2019-7-31 1:40:34 PM] Got SIGTERM, shutting down Homebridge...
Jul 31 13:40:39 COTO-HB2 systemd[1]: homebridge.service: Main process exited, code=exited, status=143/n/a
Jul 31 13:40:39 COTO-HB2 systemd[1]: homebridge.service: Unit entered failed state.
Jul 31 13:40:39 COTO-HB2 systemd[1]: homebridge.service: Failed with result 'exit-code'.

**Comment by basdelfos** [comment]
Thank you for using the plugin.
There was a typo in the errorhandling causing Homebridge to restart. I have fixed this in version 0.1.3, you can upgrade the npm package and try again.

But, as this typo was in an error handling means something is going wrong with connecting with the Tuya Web API. The fix fill probably show the error message.
