### ISSUE TITLE
How To Remove Device?

### ISSUE THREAD

**Issue by mitch7391** [basdelfos/homebridge-tuya-web#77]
I recently bought a smart light that I then ended up returning. I configured this through Smart Life app and even though I have removed it from the app, it still appears in my HomeKit. Any tips on how to remove it properly?

**Comment by Faisalthe01** [comment]
Reset accessories in homebridge settings

**Comment by mitch7391** [comment]
I have tried that with the option in config-ui-x and it did not remove it.

**Comment by mitch7391** [comment]
I deleted the plug-in and reinstalled; that fixed the issue.
