### ISSUE TITLE
New errors...

### ISSUE THREAD

**Issue by kalety** [basdelfos/homebridge-tuya-web#8]
Jul 31 18:45:13 COTO-HB2 homebridge[1041]: [2019-7-31 6:45:13 PM] [Homebridge Server] is listening on: http://192.168.0.7:8765
Jul 31 18:45:13 COTO-HB2 homebridge[1041]: [2019-7-31 6:45:13 PM] Homebridge is running on port 51828.
Jul 31 18:45:13 COTO-HB2 homebridge[1041]: [2019-7-31 6:45:13 PM] [Baño principal] Start scanning.
Jul 31 18:45:13 COTO-HB2 homebridge[1041]: [2019-7-31 6:45:13 PM] [Baño azul] Start scanning.
Jul 31 18:45:13 COTO-HB2 homebridge[1041]: [2019-7-31 6:45:13 PM] [Aseo] Start scanning.
Jul 31 18:45:18 COTO-HB2 homebridge[1041]: #033[0;37m[2019-7-31 6:45:18 PM] #033[0m#033[0;36m[Config]#033[0m #033[0;33mConsole v4.5.1 is listening on :: port 8080#033[0m
Jul 31 18:47:24 COTO-HB2 homebridge[1041]: [2019-7-31 6:47:24 PM] [TuyaWebPlatform] Error: Authentication fault, could not retreive token.
Jul 31 18:47:24 COTO-HB2 homebridge[1041]:     at Request.request [as _callback] (/usr/local/lib/node_modules/homebridge-tuya-web/lib/tuyawebapi.js:208:28)
Jul 31 18:47:24 COTO-HB2 homebridge[1041]:     at self.callback (/usr/local/lib/node_modules/homebridge-tuya-web/node_modules/request/request.js:185:22)
Jul 31 18:47:24 COTO-HB2 homebridge[1041]:     at Request.emit (events.js:198:13)
Jul 31 18:47:24 COTO-HB2 homebridge[1041]:     at Request.onRequestError (/usr/local/lib/node_modules/homebridge-tuya-web/node_modules/request/request.js:881:8)
Jul 31 18:47:24 COTO-HB2 homebridge[1041]:     at ClientRequest.emit (events.js:198:13)
Jul 31 18:47:24 COTO-HB2 homebridge[1041]:     at TLSSocket.socketErrorListener (_http_client.js:392:9)
Jul 31 18:47:24 COTO-HB2 homebridge[1041]:     at TLSSocket.emit (events.js:198:13)
Jul 31 18:47:24 COTO-HB2 homebridge[1041]:     at emitErrorNT (internal/streams/destroy.js:91:8)
Jul 31 18:47:24 COTO-HB2 homebridge[1041]:     at emitErrorAndCloseNT (internal/streams/destroy.js:59:3)
Jul 31 18:47:24 COTO-HB2 homebridge[1041]:     at process._tickCallback (internal/process/next_tick.js:63:19)

**Comment by basdelfos** [comment]
Looking at the log I see that it takes 2 minutes to get the `[TuyaWebPlatform] Error: Authentication fault, could not retreive token.`. I think some timeout is reached while trying to do a http request to the authentication server from Tuya Web API.

Are you sure that homebridge is connected to the internet?
You could try to ping `https://px1.tuyaeu.com` and see if it is reachable.

**Comment by kalety** [comment]
Yes, this was  the problem, DNS nameservers. Thank you! . The outlets with led light incorporated, only works the switch. May be in future versions?
